apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ors-frontend
      namespace: ors
    spec:
      template:
        spec:
          containers:
            - name: ors-frontend
              resources:
                requests:
                  cpu: 50m
                  memory: 52Mi
            - name: istio-proxy
              image: auto
              resources:
                requests:
                  cpu: 100m
                  memory: 120Mi
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
