apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ors-virtualservice
  namespace: ors
spec:
  hosts:
    - "ors-sro.alpha.phac-aspc.gc.ca"
  gateways:
    - istio-ingress/mesh-gateway
  http:
    - match:
        - uri:
            prefix: /ors/v2
      route:
        - destination:
            host: ors-service.ors.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ors-service.ors.svc.cluster.local
            port:
              number: 9001