apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ors-virtualservice
  namespace: ors
spec:
  hosts:
    - "ors-sro.alpha.phac-aspc.gc.ca"
  gateways:
    - istio-ingress/mesh-gateway
  http:
    - match:
        - uri:
            prefix: /ors/v2
      route:
        - destination:
            host: ors-service.ors.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /static # This is an example, adjust based on your frontend's static assets path
      route:
        - destination:
            host: ors-frontend-service.ors.svc.cluster.local
            port:
              number: 3000
    - match:
        - uri:
            exact: / # This matches the root URL
      route:
        - destination:
            host: ors-frontend-service.ors.svc.cluster.local
            port:
              number: 3000
    - match:
        - uri:
            prefix: / # This matches all other paths not matched above
      route:
        - destination:
            host: ors-frontend-service.ors.svc.cluster.local
            port:
              number: 3000