apiVersion: v1
data:
  token: eG94Yi01NTgzNjM4MTcyMjMtNTY1MzQ0NzE4Mzg3Ny1maXpxV1pnYjh0TmpGQmRoNnZUS1BXdU8=
kind: Secret
metadata:
  creationTimestamp: null
  name: slack-bot-token
  namespace: flux-system
