apiVersion: apps/v1
kind: Deployment
metadata:
  name: ors-app
  namespace: ors
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ors-app
  template:
    metadata:
      labels:
        app: ors-app
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        traffic.sidecar.istio.io/excludeOutboundPorts: "443"
    spec:
      serviceAccountName: gcs-access-sa
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /home/ors/config /home/ors/graphs /home/ors/elevation_cache /home/ors/files /home/ors/logs && chmod -R 777 /home/ors"]
          volumeMounts:
            - name: ors-storage
              mountPath: /home/ors
        - name: download-osm-data
          image: google/cloud-sdk:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              mkdir -p /home/ors/files &&
              if [ -f /home/ors/files/canada-latest.osm.pbf ]; then
                echo "OSM file already exists. Skipping download.";
              else
                echo "Downloading OSM file..." &&
                gsutil cp gs://canada-osm/canada-latest.osm.pbf /home/ors/files/canada-latest.osm.pbf &&
                if [ ! -f /home/ors/files/canada-latest.osm.pbf ]; then
                  echo "OSM file not downloaded!";
                  exit 1;
                fi &&
                echo "OSM file downloaded successfully.";
              fi &&
              ls -l /home/ors/files/canada-latest.osm.pbf
          volumeMounts:
            - name: ors-storage
              mountPath: /home/ors
        - name: build-graphs
          image: openrouteservice/openrouteservice:v8.1.1
          command: ["/bin/bash", "/home/ors/graphs.sh", "build"]
          resources:
            requests:
              cpu: "1000m"
              memory: "8Gi"
            limits:
              cpu: "2000m"
              memory: "16Gi"
          volumeMounts:
            - name: ors-storage
              mountPath: /home/ors
            - name: scripts
              mountPath: /home/ors/graphs.sh
              subPath: graphs.sh
      containers:
        - name: ors-app
          image: openrouteservice/openrouteservice:v8.1.1
          ports:
            - containerPort: 8082
            - containerPort: 9001
          env:
            - name: REBUILD_GRAPHS
              value: "False"
            - name: CONTAINER_LOG_LEVEL
              value: "INFO"
            - name: XMS
              value: "1g"
            - name: XMX
              value: "2g"
            - name: ADDITIONAL_JAVA_OPTS
              value: ""
          volumeMounts:
            - name: ors-storage
              mountPath: /home/ors
            - name: config-volume
              mountPath: /home/ors/config
          resources:
            requests:
              cpu: 500m
              memory: 2.5Gi
            limits:
              cpu: 1000m
              memory: 10Gi
      volumes:
        - name: ors-storage
          persistentVolumeClaim:
            claimName: ors-pvc
        - name: config-volume
          configMap:
            name: ors-config
            items:
              - key: application.properties
                path: application.properties
        - name: scripts
          configMap:
            name: ors-graphs-cm
            items:
              - key: graphs.sh
                path: graphs.sh