apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ors-app
      namespace: ors
    spec:
      template:
        spec:
          containers:
            - name: istio-proxy
              image: auto
              resources:
                requests:
                  cpu: 50m
                  memory: 52Mi
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: ors-sa
      namespace: ors
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: ors-sa@phx-01j3dtrkz4x.iam.gserviceaccount.com