apiVersion: v1
kind: ConfigMap
metadata:
  name: ors-graph-script
  namespace: ors
data:
  graphs.sh: |
    #!/bin/bash

    set -e

    echo "Starting the graph build process..."

    # Download the latest ORS JAR file
    echo "Downloading ORS JAR..."
    mkdir -p /home/ors/jar
    wget -O /home/ors/jar/ors.jar https://github.com/GIScience/openrouteservice/releases/download/v8.1.2/ors.jar
    echo "ORS JAR downloaded successfully."

    # Run the build command
    java -jar /home/ors/jar/ors.jar --graphs --data-sources /home/ors/files/canada-latest.osm.pbf

    echo "Graphs built successfully."
