apiVersion: v1
kind: ConfigMap
metadata:
  name: ors-graphs-cm
  namespace: ors
data:
  graphs.sh: |
    #!/bin/bash

    echo "Starting to build graphs..."

    # Command to build graphs using the downloaded ORS JAR
    java -jar /home/ors/jar/ors.jar --graphs --data-sources /home/ors/files/canada-latest.osm.pbf

    echo "Graphs built successfully."
