apiVersion: v1
kind: Service
metadata:
  name: ors-service
  namespace: ors
spec:
  selector:
    app: ors-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8082
    - name: monitoring
      protocol: TCP
      port: 9001
      targetPort: 9001
