apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: "localtrace"
  metrics:
  - providers:
    - name: "prometheus"
  accessLogging:
  - providers:
    - name: "envoy"